apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-service
    tier: backend
    run: config-service
    visualize: "true"
  name: config-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    app: config-service
    tier: backend
