apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: config-service
    visualize: "true"
  name: config-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: config-service
        tier: backend
        track: stable
        run: config-service
        visualize: "true"
    spec:
      containers:
      - image: kubecloud/demo-itonk-grp3-config-service:v1
        name: config-service
  minReadySeconds: 120
