apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
    tier: backend
    run: order-service
    visualize: "true"
  name: order-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: order-service
    tier: backend
