apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: order-service
    visualize: "true"
  name: order-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: order-service
        tier: backend
        track: stable
        run: order-service
        visualize: "true"
    spec:
      containers:
      - image: kubecloud/demo-itonk-grp3-order-service:v1
        name: order-service
  minReadySeconds: 120
