apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: web-service
    visualize: "true"
  name: web-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-service
        tier: backend
        track: stable
        run: web-service
        visualize: "true"
    spec:
      containers:
      - image: kubecloud/demo-itonk-grp3-web-service:v1
        name: web-service
  minReadySeconds: 120
