apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-service
    tier: backend
    run: web-service
    visualize: "true"
  name: web-service
spec:
  ports:
  - port: 9005
    protocol: TCP
    targetPort: 9005
  selector:
    app: web-service
    tier: backend
