apiVersion: v1
kind: Service
metadata:
  labels:
    app: website
    tier: frontend
    run: website
    visualize: "true"
  name: website
spec:
  ports:
  - port: 8080 # Exposed port on cluster
    protocol: TCP
    targetPort: 8080 # Internal service port
  selector:
    app: website
    tier: frontend
